{"uid":"8db98430c6c6fa81","name":"test_TC227_Verificar_error_al_crear_opcion_con_position_mayor_a_999999999","fullName":"tests.catalog.options.test_HU11_ES_POST_ProductOption#test_TC227_Verificar_error_al_crear_opcion_con_position_mayor_a_999999999","historyId":"09c4f63e9a9984c5936c41cb895fd765","time":{"start":1755544227625,"stop":1755544228436,"duration":811},"status":"skipped","statusMessage":"XFAIL Known issue BUG: Error 500 (Internal Server Error) inapropiado al validar campo numérico\n\nAssertionError","statusTrace":"setup_add_options = ({'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NTU1NDM5NTUsImV4cCI6MTc1NTU0NzU1NSwicm9sZX...MoXXV_pqSUStd2aWF01HHdQEbAg9mOihi6J2QILYyA4m45ho_z3kDnFQzjq1YotTqqiieb2f4Pz_sa4KhDJzMgrPVKiwQTkepKI2qZmuSeq4WJf4'}, [])\n\n    @pytest.mark.functional\n    @pytest.mark.boundary\n    @pytest.mark.medium\n    @pytest.mark.xfail(reason=\"Known issue BUG: Error 500 (Internal Server Error) inapropiado al validar campo numérico\", run=True)\n    def test_TC227_Verificar_error_al_crear_opcion_con_position_mayor_a_999999999(setup_add_options):\n        headers, _ = setup_add_options\n        payload = generate_options_source_data()\n        payload[\"position\"] = fake.random_int(min=1000000000, max=10000000000)\n        response = SyliusRequest.post(EndpointOptions.options(), headers, payload)\n        log_request_response(EndpointOptions.options(), response, headers, payload)\n>       AssertionStatusCode.assert_status_code_422(response)\n\ntests/catalog/options/test_HU11_ES_POST_ProductOption.py:184: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_422(response):\n>       assert response.status_code == 422\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       AssertionError\n\nsrc/assertions/status_code_assertions.py:59: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1755543954615,"stop":1755543954615,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"auth_headers","time":{"start":1755543954616,"stop":1755543956074,"duration":1458},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"setup_add_options","time":{"start":1755544227625,"stop":1755544227625,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"skipped","statusMessage":"XFAIL Known issue BUG: Error 500 (Internal Server Error) inapropiado al validar campo numérico\n\nAssertionError","statusTrace":"setup_add_options = ({'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3NTU1NDM5NTUsImV4cCI6MTc1NTU0NzU1NSwicm9sZX...MoXXV_pqSUStd2aWF01HHdQEbAg9mOihi6J2QILYyA4m45ho_z3kDnFQzjq1YotTqqiieb2f4Pz_sa4KhDJzMgrPVKiwQTkepKI2qZmuSeq4WJf4'}, [])\n\n    @pytest.mark.functional\n    @pytest.mark.boundary\n    @pytest.mark.medium\n    @pytest.mark.xfail(reason=\"Known issue BUG: Error 500 (Internal Server Error) inapropiado al validar campo numérico\", run=True)\n    def test_TC227_Verificar_error_al_crear_opcion_con_position_mayor_a_999999999(setup_add_options):\n        headers, _ = setup_add_options\n        payload = generate_options_source_data()\n        payload[\"position\"] = fake.random_int(min=1000000000, max=10000000000)\n        response = SyliusRequest.post(EndpointOptions.options(), headers, payload)\n        log_request_response(EndpointOptions.options(), response, headers, payload)\n>       AssertionStatusCode.assert_status_code_422(response)\n\ntests/catalog/options/test_HU11_ES_POST_ProductOption.py:184: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [500]>\n\n    @staticmethod\n    def assert_status_code_422(response):\n>       assert response.status_code == 422\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       AssertionError\n\nsrc/assertions/status_code_assertions.py:59: AssertionError","steps":[],"attachments":[{"uid":"ff922311d99d367","name":"log","source":"ff922311d99d367.txt","type":"text/plain","size":1971}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"setup_add_options::0","time":{"start":1755544228443,"stop":1755544228443,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"tag","value":"medium"},{"name":"tag","value":"boundary"},{"name":"tag","value":"functional"},{"name":"parentSuite","value":"tests.catalog.options"},{"name":"suite","value":"test_HU11_ES_POST_ProductOption"},{"name":"host","value":"pkrvmubgrv54qmi"},{"name":"thread","value":"2416-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.catalog.options.test_HU11_ES_POST_ProductOption"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["boundary","functional","medium"]},"source":"8db98430c6c6fa81.json","parameterValues":[]}